### ISSUE TITLE
What's the source of seg2d (input of 'process_msk' in data processing)?

### ISSUE THREAD

**Issue by chengzhag** [thusiyuan/cooperative_scene_parsing#16]
Hi Siyuan:

Thanks for sharing the code of your work!

I noticed that the 2D detector and the data cleaning code for generating the pickle files are not included in this repo. I read into the processing code for the cleaned data to find that the function 'process_msk' utilizes the 2dbbox from the detector (is it so?) and semantic segmentation GT to get reasonable masks from the candidates. 

However, the candidates are drawn from polygon input 'seg2d' whose source is not known. Is it from the SUNRGBD dataset? Or is it from the output of the 2D detector?

**Comment by gilbert248** [comment]
@chengzhag hello! the answer to your question is very important. recently i have been digging in single image 3d object detection, then i found many methods(e.g. total3d) used this data process procedure. could you please teach me where is this 2d detection data come from?
