### ISSUE TITLE
hard-coded path in the pickle file

### ISSUE THREAD

**Issue by ZheC** [thusiyuan/cooperative_scene_parsing#2]
You have some hard-coded path in the pickle files, e.g., in this line: https://github.com/thusiyuan/cooperative_scene_parsing/blob/master/preprocess/sunrgbd/sunrgbd_parser.py#L116 

img_info['imgrgb_path']
'/home/siyuan/Documents/Dataset/SUNRGBD_ALL/SUNRGBD/kv2/kinect2data/000002_2014-05-26_14-23-37_260595134347_rgbf000103-resize/image/0000103.jpg'

img_info['imgdepth_path']
'/home/siyuan/Documents/Dataset/SUNRGBD_ALL/SUNRGBD/kv2/kinect2data/000002_2014-05-26_14-23-37_260595134347_rgbf000103-resize/depth/0000103.png'

Could you add your code to generate the pickle files as well? Also, it seems in your preprocessed data, there is no depth images, should I download the original SUNRGBD dataset as well?

**Comment by thusiyuan** [comment]
Hi,

Thank you for pointing it out.

I manually change the root temporarily as in https://github.com/thusiyuan/cooperative_scene_parsing/commit/472417abc8eb60343d848739b7ff2d5fa73e6ba2

You also need to download the original dataset, as added in README.

We will prepare the code for generating the pickles files, hopefully, will release them in next month, maybe after the ICCV deadline.

Thank you.

**Comment by ZheC** [comment]
Thank you for fixing that. That's helpful! 

One more question: in this line: img_info['seg2d'] = loadmat(img_info['seg2d_path'])['seg_2d']
'/home/siyuan/Documents/cvpr2018/data_temp/segmentation/1.mat' 

Where can we download the segmentation files?

**Comment by thusiyuan** [comment]
This is the segmentation map we generate for another project.

You could comment out this line.

**Comment by ZheC** [comment]
Could you kindly share these segmentation files? I was intended to implement a function to visualize the 3d point cloud with semantic information and the corresponding 3d bounding box. Having these segmentation maps will be super helpful! Thank you for the useful code and preprocessed data!

**Comment by thusiyuan** [comment]
https://drive.google.com/file/d/1T-POZBhkh1YW9W0JG2qgVSb_tnvjoHXx/view?usp=sharing

This is the segmentation file we use. You can use it after changing the seg root in the pickle file.

To be noticed, the seg results are not ground truth but inferred from a learned segmentation model. If you want the ground truth, you may need to process the original dataset.

If you want to do visualization, it should be enough.
