### ISSUE TITLE
missing visualization functions

### ISSUE THREAD

**Issue by ZheC** [thusiyuan/cooperative_scene_parsing#3]
Hey, could you also provide the code for the visualization functions: [show_3dpointcloud](https://github.com/thusiyuan/cooperative_scene_parsing/blob/8605cf02aaba3fd2af3eb7e285bcea9966158984/preprocess/sunrgbd/sunrgbd_parser.py#L158), show_3dpointcloud_aligned and show_2dcorner. It will be helpful for debugging purpose! Thank you!

**Comment by thusiyuan** [comment]
Please check it from https://github.com/thusiyuan/cooperative_scene_parsing/commit/75b10806dbdd44eaf94be9d66ce44fcb68969098

Thanks

**Comment by ZheC** [comment]
Great, thank you, it works!
