### ISSUE TITLE
Link of raw data of sunrgbd has broken.

### ISSUE THREAD

**Issue by expert668** [thusiyuan/cooperative_scene_parsing#4]
Link of raw data of sunrgbd has broken. Is the raw data of sunrgbd downloaded from the http://rgbd.cs.princeton.edu/challenge.html?

Thank the great work you have done!

**Comment by thusiyuan** [comment]
I just fixed the broken link.

Thanks!

**Comment by Expert68** [comment]
One more question，There's always wrong while unzip the .zip file you posed. Do you know how to solve this problem?
