### ISSUE TITLE
Test on images outside SUNRGBD dataset

### ISSUE THREAD

**Issue by ZheC** [thusiyuan/cooperative_scene_parsing#5]
Hey, I test the model and it works well in the SUNRGBD dataset! Thank you for sharing it. Could you please give any hint about how to apply the model to images outside SUNRGBD dataset? Should I generate a pickle file following sunrgbd_process.py? Do we need any input other than the RGB image, e.g., the camera intrinsics?

**Comment by thusiyuan** [comment]
The inputs are only an RGB image and camera intrinsic matrix.

You should first detect 2D bounding boxes and feed the image patches and original image into LON and GGN to estimate the local objects and global geometry with attributes.

We may release the inference code in the future.

**Comment by wellowdata** [comment]
Hi, thank you for sharing this, it is a great project. Do you have any update on whether you will share the inference code?

Thanks
