### ISSUE TITLE
Are ground-truth files in metadata preprocessed

### ISSUE THREAD

**Issue by shubham-goel** [thusiyuan/cooperative_scene_parsing#7]
Hi!

Most of the code uses mat/pickle files present in the `metadata/sunrgbd/` folder as ground truth. A few examples of the files being used are: 

- `metadata/sunrgbd/Dataset/data_clean/data_all/` in `sunrgbd_parser.py`
- `metadata/sunrgbd/2dbdb/` in `sunrgbd_process.py`
- `metadata/sunrgbd/3dlayout/` in `sunrgbd_process.py`

Are they simply a reorganization of the ground truth data (`SUNRGBDMeta2DBB_v2.mat`, `SUNRGBDMeta3DBB_v2.mat`, etc.) provided by the SUNRGBD dataset, or have you performed any additional processing?

Thanks,
Shubham

**Comment by thusiyuan** [comment]
Hi,

Those are simply the reorganization of the original mat file except the 3D layout. The original layouts are 3D polygons, we use the Manhattan World assumption to process them as 3D cuboid.

Best,
Siyuan
