### ISSUE TITLE
local variable 'corner_loss' referenced before assignment

### ISSUE THREAD

**Issue by XGBoost** [thusiyuan/cooperative_scene_parsing#8]
Hi, Siyuan
When I train the bdbnet from scratch by
`sh scripts/sunrgbd_train_bdbnet.sh`, it reminded me that 
![image](https://user-images.githubusercontent.com/23393128/55378672-847a6500-554c-11e9-9a7e-8cf36baef0b2.png).
Thank u !
Yongjie

**Comment by thusiyuan** [comment]
Hi, 

I have updated the code.

You could try it now.

Siyuan

**Comment by XGBoost** [comment]
It is solved!
Thank you very much!
Yongjie
